# Generated by Django 5.1.1 on 2024-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profilemodel_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
