# Generated by Django 5.1.1 on 2024-09-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profilemodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='about',
            field=models.CharField(blank=True, default='This is the default about', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(blank=True, default='static/img/default.webp', null=True, upload_to='Profile'),
        ),
    ]
