# Generated by Django 5.1.1 on 2024-09-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_remove_profilemodel_name_remove_profilemodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='about',
            field=models.CharField(blank=True, default='Default about', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(blank=True, default='Default description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/default.webp', null=True, upload_to='Profile'),
        ),
    ]
