# Generated by Django 5.1.1 on 2024-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profilemodel_about_alter_profilemodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='description',
            field=models.TextField(blank=True, default='Default description', null=True),
        ),
    ]
