# Generated by Django 5.1.1 on 2024-11-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profilemodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='status',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff'), ('Employee', 'Employee'), ('Intern', 'Intern'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave'), ('Retired', 'Retired'), ('Junior Staff', 'Junior Staff'), ('Senior Staff', 'Senior Staff'), ('Lead', 'Lead')], default='Staff', max_length=20),
        ),
    ]
