# Generated by Django 5.1.1 on 2024-11-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_profilemodel_facebook_profilemodel_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='telegram',
        ),
    ]
