# Generated by Django 5.1.1 on 2025-01-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_remove_profilemodel_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
