# Generated by Django 5.1.1 on 2024-09-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Category logo'),
        ),
        migrations.AddField(
            model_name='departments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments'),
        ),
    ]
