# Generated by Django 5.1.1 on 2024-09-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='Blog')),
            ],
        ),
    ]
