# Generated by Django 5.1.1 on 2024-10-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_blogpost_tag_delete_blog_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product'),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
