# Generated by Django 5.1.1 on 2024-10-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_remove_billing_details_state_billing_details_street_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_details',
            old_name='Street',
            new_name='street',
        ),
    ]
