# Generated by Django 5.1.1 on 2024-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_cart_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='p_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
