# Generated by Django 5.1.1 on 2024-10-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_alter_product_discount_percentage_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Discount in percentage (e.g.., 10 for 10%)', max_digits=6)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
