# Generated by Django 5.1.1 on 2024-10-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_supplier_product_product_video_product_shipping_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='selles',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='Main.product'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
