# Generated by Django 5.1.1 on 2024-10-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_remove_product_supplier_product_selles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selles',
            field=models.IntegerField(default=0),
        ),
    ]
