# Generated by Django 5.1.1 on 2024-10-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_alter_product_selles'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mission_statement', models.CharField(blank=True, max_length=255)),
                ('vision', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='Project/')),
                ('banner', models.ImageField(upload_to='Project/')),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('support_contact', models.CharField(blank=True, max_length=100)),
                ('operating_hours', models.CharField(blank=True, max_length=100)),
                ('map_location', models.URLField(blank=True)),
                ('testimonials', models.TextField(blank=True)),
                ('team_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=400)),
                ('logo', models.ImageField(upload_to='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=400)),
                ('logo', models.ImageField(upload_to='Project')),
            ],
        ),
    ]
