# Generated by Django 5.1.1 on 2024-10-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_about_paymentmethod_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='url',
            new_name='link',
        ),
    ]
