# Generated by Django 5.1.1 on 2024-10-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_rename_url_paymentmethod_link_rename_url_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
