# Generated by Django 5.1.1 on 2024-10-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='about',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
