# Generated by Django 5.1.1 on 2024-10-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_order_delete_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
