# Generated by Django 5.1.1 on 2024-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0035_delivery_delete_order'),
        ('Profile', '0006_alter_profilemodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='about_pages', to='Profile.profilemodel'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
