# Generated by Django 5.1.1 on 2024-11-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0037_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specialDiscountPrice',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
