# Generated by Django 5.1.1 on 2024-11-04 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0038_product_specialdiscountprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specialDiscountPrice',
        ),
    ]
