# Generated by Django 5.1.1 on 2024-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0039_remove_product_specialdiscountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SpecialOffer_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
