# Generated by Django 5.1.1 on 2024-11-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0040_product_specialoffer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
