# Generated by Django 5.1.1 on 2024-11-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0042_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
