# Generated by Django 5.1.1 on 2024-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0043_delivery_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
