# Generated by Django 5.1.1 on 2024-11-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0044_faq_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
