# Generated by Django 5.1.1 on 2024-11-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0048_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
