# Generated by Django 5.1.1 on 2025-01-06 08:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0050_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentTID',
        ),
    ]
